### ISSUE TITLE
Support for Github Enterprise?!

### ISSUE THREAD

**Issue by rngtng** [ahume/github-deployment-resource#3]
I'm trying to apply this resource to our inhouse concourse + Github Enterprise setup. Unfortunately I got an errror (see below). Interresting part here is that it tries to connect to `https://api.github.com` even so  `github_api_url` parameter is set to our inhouse installation. What I could not read in code is, if it's actually used?

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
getting deployments list
[31merror running command: GET https://api.github.com/repos/digital-banking/solaris-logging-ruby/deployments: 401 Bad credentials []
[0mgoroutine 1 [running]:
runtime/debug.Stack(0x16, 0xc420045d98, 0x2)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/ahume/github-deployment-resource.Fatal(0x6c3200, 0xf, 0x7d7bc0, 0xc42019e0a0)
	/go/src/github.com/ahume/github-deployment-resource/fmt.go:13 +0x120
main.main()
	/go/src/github.com/ahume/github-deployment-resource/cmd/check/check.go:22 +0x28d
```

Thanks, Tobi

**Comment by iautom8things** [comment]
@rngtng Are you just now giving this resource a try, and you haven't gotten it to work?  Or have you had success and it just now stopped working?

I ask because I've been using this deployment resource for almost a year now (granted, I'm using `github.com`) and, out of nowhere yesterday I started to have issues where the `check` task is no longer triggering / seeing new deployments, even though they exist.  I'm currently trying to debug it to figure out what's happening.

It most likely is just coincidental/irrelevant that you're also having issue.  I'll be digging back into the source of this resource, I'll try to take a look for what could be causing your issue too.

**Comment by iautom8things** [comment]
I just found my issue.  I'll send up a PR shortly.  It's related to how ids are compared (recently deployment ids on github rolled over `99,999,999` so the resource is failing to properly compare these ids.  It looks like it is comparing strings, not as ints: https://github.com/ahume/github-deployment-resource/blob/master/check_command.go#L47

**Comment by rngtng** [comment]
@mazubieta thx for your quick response -  it's the first time I'm using it. [Looking at this code](https://github.com/ahume/github-deployment-resource/blob/9e7e43f53e4fe88d550575730df65bf8f07c4317/github.go#L113-L124), I can't find any usage of `GitHubAPIURL`. 
IMHO the `client.BaseURL` needs to be set. I'll prepare a PR for that..

**Comment by rngtng** [comment]
see https://github.com/google/go-github/blob/8292762dd9ba159a72c98ca47f390fdb17b1f636/github/github.go#L135
